### ISSUE TITLE
To add

### ISSUE THREAD

**Issue by LukyVj** [bullgit/unicood.es#5]
- ~~http://www.fileformat.info/info/unicode/char/a.htm~~
- ~~http://jrgraphix.net/r/Unicode/2600-26FF~~
- ~~http://panmental.de/symbols/info.htm~~
- ~~http://unicodeemoticons.com/cool_text_icons_and_pictures.htm~~

**Comment by Haroenv** [comment]
- ~~http://unicode-table.com/en/~~
- ~~http://shapecatcher.com~~

**Comment by LukyVj** [comment]
This one is already in the list, I'll update the repo in some minutes

**Comment by Haroenv** [comment]
Ah, looking forward to see it.
